/**
 * Bundled art catalogue — GENERATED, do not edit by hand.
 * Regenerate with `npm run assets:manifest` after adding files to public/assets.
 *
 * Actor, marker and arena art comes from XIVPlan (github.com/joelspadin/xivplan,
 * MIT). Mechanic telegraphs come from the FFXIV Strategy Board asset set.
 * See NOTICE.md.
 */

/** Asset key ("actor/WAR") -> file under /assets. */
export const ASSETS: Record<string, string> = {
  "actor/AST": "actor/AST.png",
  "actor/BLM": "actor/BLM.png",
  "actor/BLU": "actor/BLU.png",
  "actor/BRD": "actor/BRD.png",
  "actor/BST": "actor/BST.png",
  "actor/DNC": "actor/DNC.png",
  "actor/DRG": "actor/DRG.png",
  "actor/DRK": "actor/DRK.png",
  "actor/GNB": "actor/GNB.png",
  "actor/MCH": "actor/MCH.png",
  "actor/MNK": "actor/MNK.png",
  "actor/NIN": "actor/NIN.png",
  "actor/PCT": "actor/PCT.png",
  "actor/PLD": "actor/PLD.png",
  "actor/RDM": "actor/RDM.png",
  "actor/RPR": "actor/RPR.png",
  "actor/SAM": "actor/SAM.png",
  "actor/SCH": "actor/SCH.png",
  "actor/SGE": "actor/SGE.png",
  "actor/SMN": "actor/SMN.png",
  "actor/VPR": "actor/VPR.png",
  "actor/WAR": "actor/WAR.png",
  "actor/WHM": "actor/WHM.png",
  "actor/any": "actor/any.png",
  "actor/barrier_healer": "actor/barrier_healer.png",
  "actor/boss": "actor/boss.svg",
  "actor/dps": "actor/dps.png",
  "actor/dps1": "actor/dps1.png",
  "actor/dps2": "actor/dps2.png",
  "actor/dps3": "actor/dps3.png",
  "actor/dps4": "actor/dps4.png",
  "actor/enemy": "actor/enemy.png",
  "actor/enemy1": "actor/enemy1.png",
  "actor/enemy2": "actor/enemy2.png",
  "actor/enemy3": "actor/enemy3.png",
  "actor/enemy_circle": "actor/enemy_circle.png",
  "actor/enemy_huge": "actor/enemy_huge.png",
  "actor/enemy_large": "actor/enemy_large.png",
  "actor/enemy_medium": "actor/enemy_medium.png",
  "actor/enemy_small": "actor/enemy_small.png",
  "actor/healer": "actor/healer.png",
  "actor/healer1": "actor/healer1.png",
  "actor/healer2": "actor/healer2.png",
  "actor/magic_ranged": "actor/magic_ranged.png",
  "actor/melee": "actor/melee.png",
  "actor/melee1": "actor/melee1.png",
  "actor/melee2": "actor/melee2.png",
  "actor/physical_ranged": "actor/physical_ranged.png",
  "actor/pure_healer": "actor/pure_healer.png",
  "actor/ranged": "actor/ranged.png",
  "actor/ranged1": "actor/ranged1.png",
  "actor/ranged2": "actor/ranged2.png",
  "actor/support": "actor/support.png",
  "actor/tank": "actor/tank.png",
  "actor/tank1": "actor/tank1.png",
  "actor/tank2": "actor/tank2.png",
  "marker/attack1": "marker/attack1.png",
  "marker/attack2": "marker/attack2.png",
  "marker/attack3": "marker/attack3.png",
  "marker/attack4": "marker/attack4.png",
  "marker/attack5": "marker/attack5.png",
  "marker/attack6": "marker/attack6.png",
  "marker/attack7": "marker/attack7.png",
  "marker/attack8": "marker/attack8.png",
  "marker/bind1": "marker/bind1.png",
  "marker/bind2": "marker/bind2.png",
  "marker/bind3": "marker/bind3.png",
  "marker/bind4": "marker/bind4.png",
  "marker/bind5": "marker/bind5.png",
  "marker/bind6": "marker/bind6.png",
  "marker/bind7": "marker/bind7.png",
  "marker/bind8": "marker/bind8.png",
  "marker/blue_circle": "marker/blue_circle.png",
  "marker/circle": "marker/circle.png",
  "marker/cross": "marker/cross.png",
  "marker/crosshairs": "marker/crosshairs.png",
  "marker/dice1": "marker/dice1.png",
  "marker/dice2": "marker/dice2.png",
  "marker/dice3": "marker/dice3.png",
  "marker/eye": "marker/eye.png",
  "marker/green_circle": "marker/green_circle.png",
  "marker/green_target": "marker/green_target.png",
  "marker/ignore1": "marker/ignore1.png",
  "marker/ignore2": "marker/ignore2.png",
  "marker/ignore3": "marker/ignore3.png",
  "marker/ignore4": "marker/ignore4.png",
  "marker/ignore5": "marker/ignore5.png",
  "marker/ignore6": "marker/ignore6.png",
  "marker/ignore7": "marker/ignore7.png",
  "marker/ignore8": "marker/ignore8.png",
  "marker/limit1": "marker/limit1.png",
  "marker/limit2": "marker/limit2.png",
  "marker/limit3": "marker/limit3.png",
  "marker/limit4": "marker/limit4.png",
  "marker/limit5": "marker/limit5.png",
  "marker/limit6": "marker/limit6.png",
  "marker/limit7": "marker/limit7.png",
  "marker/limit8": "marker/limit8.png",
  "marker/plus": "marker/plus.png",
  "marker/proximity": "marker/proximity.png",
  "marker/red_target": "marker/red_target.png",
  "marker/shape_circle": "marker/shape_circle.png",
  "marker/shape_cross": "marker/shape_cross.png",
  "marker/shape_square": "marker/shape_square.png",
  "marker/shape_triangle": "marker/shape_triangle.png",
  "marker/square": "marker/square.png",
  "marker/tankbuster": "marker/tankbuster.png",
  "marker/target_blue": "marker/target_blue.png",
  "marker/target_crosshairs": "marker/target_crosshairs.png",
  "marker/target_green": "marker/target_green.png",
  "marker/target_purple": "marker/target_purple.png",
  "marker/target_red": "marker/target_red.png",
  "marker/triangle": "marker/triangle.png",
  "marker/waymark_1": "marker/waymark_1.png",
  "marker/waymark_2": "marker/waymark_2.png",
  "marker/waymark_3": "marker/waymark_3.png",
  "marker/waymark_4": "marker/waymark_4.png",
  "marker/waymark_a": "marker/waymark_a.png",
  "marker/waymark_b": "marker/waymark_b.png",
  "marker/waymark_c": "marker/waymark_c.png",
  "marker/waymark_d": "marker/waymark_d.png",
  "marker/eden/blue": "marker/eden/blue.png",
  "marker/eden/orange": "marker/eden/orange.png",
  "marker/eden/yellow": "marker/eden/yellow.png",
  "marker/ultimate/circle": "marker/ultimate/circle.png",
  "marker/ultimate/cross": "marker/ultimate/cross.png",
  "marker/ultimate/square": "marker/ultimate/square.png",
  "marker/ultimate/triangle": "marker/ultimate/triangle.png",
  "mechanic/circle-aoe": "mechanic/circle-aoe.png",
  "mechanic/four-person-aoe": "mechanic/four-person-aoe.png",
  "mechanic/gaze": "mechanic/gaze.png",
  "mechanic/line-stack": "mechanic/line-stack.png",
  "mechanic/linear-knockback": "mechanic/linear-knockback.png",
  "mechanic/moving-circle-aoe": "mechanic/moving-circle-aoe.png",
  "mechanic/multi-hit-stack": "mechanic/multi-hit-stack.png",
  "mechanic/one-person-aoe": "mechanic/one-person-aoe.png",
  "mechanic/player-proximity": "mechanic/player-proximity.png",
  "mechanic/proximity": "mechanic/proximity.png",
  "mechanic/radial-knockback": "mechanic/radial-knockback.png",
  "mechanic/single-target-tankbuster": "mechanic/single-target-tankbuster.png",
  "mechanic/stack": "mechanic/stack.png",
  "mechanic/targeting-indicator": "mechanic/targeting-indicator.png",
  "mechanic/three-person-aoe": "mechanic/three-person-aoe.png",
  "mechanic/tower-ring-met": "mechanic/tower-ring-met.png",
  "mechanic/tower-ring": "mechanic/tower-ring.png",
  "mechanic/tower": "mechanic/tower.png",
  "mechanic/two-person-aoe": "mechanic/two-person-aoe.png",
  "arena/arcadion11-split-v2": "arena/arcadion11-split-v2.svg",
  "arena/arcadion11-split": "arena/arcadion11-split.svg",
  "arena/arcadion11": "arena/arcadion11.svg",
  "arena/arcadion12-p2-split": "arena/arcadion12-p2-split.svg",
  "arena/arcadion12-p2-v2": "arena/arcadion12-p2-v2.svg",
  "arena/arcadion12-p2": "arena/arcadion12-p2.svg",
  "arena/arcadion12": "arena/arcadion12.svg",
  "arena/arcadion2": "arena/arcadion2.svg",
  "arena/arcadion3": "arena/arcadion3.svg",
  "arena/arcadion4-p2": "arena/arcadion4-p2.svg",
  "arena/arcadion4": "arena/arcadion4.svg",
  "arena/arcadion6-quicksand": "arena/arcadion6-quicksand.svg",
  "arena/arcadion6-quicksand2": "arena/arcadion6-quicksand2.svg",
  "arena/arcadion6-river": "arena/arcadion6-river.svg",
  "arena/arcadion6-volcano": "arena/arcadion6-volcano.svg",
  "arena/arcadion6": "arena/arcadion6.svg",
  "arena/arcadion7-p2": "arena/arcadion7-p2.svg",
  "arena/arcadion7-p3": "arena/arcadion7-p3.svg",
  "arena/arcadion7": "arena/arcadion7.svg",
  "arena/arcadion8-p2": "arena/arcadion8-p2.svg",
  "arena/arcadion8-sp2-mirror": "arena/arcadion8-sp2-mirror.svg",
  "arena/arcadion8-sp2": "arena/arcadion8-sp2.svg",
  "arena/arcadion8": "arena/arcadion8.svg",
  "arena/cloud-deck": "arena/cloud-deck.svg",
  "arena/e11": "arena/e11.svg",
  "arena/e8": "arena/e8.svg",
  "arena/everkeep": "arena/everkeep.svg",
  "arena/jury_light": "arena/jury_light.jpg",
  "arena/p10": "arena/p10.svg",
  "arena/p11": "arena/p11.svg",
  "arena/p12-p2": "arena/p12-p2.svg",
  "arena/p12": "arena/p12.svg",
  "arena/p12_checker": "arena/p12_checker.svg",
  "arena/p12_checker2": "arena/p12_checker2.svg",
  "arena/p12_octagon": "arena/p12_octagon.svg",
  "arena/p7": "arena/p7.svg",
};

export const ACTOR_KEYS: readonly string[] = [
  "actor/AST",
  "actor/BLM",
  "actor/BLU",
  "actor/BRD",
  "actor/BST",
  "actor/DNC",
  "actor/DRG",
  "actor/DRK",
  "actor/GNB",
  "actor/MCH",
  "actor/MNK",
  "actor/NIN",
  "actor/PCT",
  "actor/PLD",
  "actor/RDM",
  "actor/RPR",
  "actor/SAM",
  "actor/SCH",
  "actor/SGE",
  "actor/SMN",
  "actor/VPR",
  "actor/WAR",
  "actor/WHM",
  "actor/any",
  "actor/barrier_healer",
  "actor/boss",
  "actor/dps",
  "actor/dps1",
  "actor/dps2",
  "actor/dps3",
  "actor/dps4",
  "actor/enemy",
  "actor/enemy1",
  "actor/enemy2",
  "actor/enemy3",
  "actor/enemy_circle",
  "actor/enemy_huge",
  "actor/enemy_large",
  "actor/enemy_medium",
  "actor/enemy_small",
  "actor/healer",
  "actor/healer1",
  "actor/healer2",
  "actor/magic_ranged",
  "actor/melee",
  "actor/melee1",
  "actor/melee2",
  "actor/physical_ranged",
  "actor/pure_healer",
  "actor/ranged",
  "actor/ranged1",
  "actor/ranged2",
  "actor/support",
  "actor/tank",
  "actor/tank1",
  "actor/tank2",
];

export const MARKER_KEYS: readonly string[] = [
  "marker/attack1",
  "marker/attack2",
  "marker/attack3",
  "marker/attack4",
  "marker/attack5",
  "marker/attack6",
  "marker/attack7",
  "marker/attack8",
  "marker/bind1",
  "marker/bind2",
  "marker/bind3",
  "marker/bind4",
  "marker/bind5",
  "marker/bind6",
  "marker/bind7",
  "marker/bind8",
  "marker/blue_circle",
  "marker/circle",
  "marker/cross",
  "marker/crosshairs",
  "marker/dice1",
  "marker/dice2",
  "marker/dice3",
  "marker/eye",
  "marker/green_circle",
  "marker/green_target",
  "marker/ignore1",
  "marker/ignore2",
  "marker/ignore3",
  "marker/ignore4",
  "marker/ignore5",
  "marker/ignore6",
  "marker/ignore7",
  "marker/ignore8",
  "marker/limit1",
  "marker/limit2",
  "marker/limit3",
  "marker/limit4",
  "marker/limit5",
  "marker/limit6",
  "marker/limit7",
  "marker/limit8",
  "marker/plus",
  "marker/proximity",
  "marker/red_target",
  "marker/shape_circle",
  "marker/shape_cross",
  "marker/shape_square",
  "marker/shape_triangle",
  "marker/square",
  "marker/tankbuster",
  "marker/target_blue",
  "marker/target_crosshairs",
  "marker/target_green",
  "marker/target_purple",
  "marker/target_red",
  "marker/triangle",
  "marker/waymark_1",
  "marker/waymark_2",
  "marker/waymark_3",
  "marker/waymark_4",
  "marker/waymark_a",
  "marker/waymark_b",
  "marker/waymark_c",
  "marker/waymark_d",
  "marker/eden/blue",
  "marker/eden/orange",
  "marker/eden/yellow",
  "marker/ultimate/circle",
  "marker/ultimate/cross",
  "marker/ultimate/square",
  "marker/ultimate/triangle",
];

export const MECHANIC_KEYS: readonly string[] = [
  "mechanic/circle-aoe",
  "mechanic/four-person-aoe",
  "mechanic/gaze",
  "mechanic/line-stack",
  "mechanic/linear-knockback",
  "mechanic/moving-circle-aoe",
  "mechanic/multi-hit-stack",
  "mechanic/one-person-aoe",
  "mechanic/player-proximity",
  "mechanic/proximity",
  "mechanic/radial-knockback",
  "mechanic/single-target-tankbuster",
  "mechanic/stack",
  "mechanic/targeting-indicator",
  "mechanic/three-person-aoe",
  "mechanic/tower-ring-met",
  "mechanic/tower-ring",
  "mechanic/tower",
  "mechanic/two-person-aoe",
];

export const ARENA_BACKGROUNDS: readonly { key: string; label: string }[] = [
  { key: "arena/arcadion11-split-v2", label: "Arcadion11 split v 2" },
  { key: "arena/arcadion11-split", label: "Arcadion11 split" },
  { key: "arena/arcadion11", label: "Arcadion 11" },
  { key: "arena/arcadion12-p2-split", label: "Arcadion12 p2 split" },
  { key: "arena/arcadion12-p2-v2", label: "Arcadion12 p2 v 2" },
  { key: "arena/arcadion12-p2", label: "Arcadion12 p 2" },
  { key: "arena/arcadion12", label: "Arcadion 12" },
  { key: "arena/arcadion2", label: "Arcadion 2" },
  { key: "arena/arcadion3", label: "Arcadion 3" },
  { key: "arena/arcadion4-p2", label: "Arcadion4 p 2" },
  { key: "arena/arcadion4", label: "Arcadion 4" },
  { key: "arena/arcadion6-quicksand", label: "Arcadion6 quicksand" },
  { key: "arena/arcadion6-quicksand2", label: "Arcadion6 quicksand 2" },
  { key: "arena/arcadion6-river", label: "Arcadion6 river" },
  { key: "arena/arcadion6-volcano", label: "Arcadion6 volcano" },
  { key: "arena/arcadion6", label: "Arcadion 6" },
  { key: "arena/arcadion7-p2", label: "Arcadion7 p 2" },
  { key: "arena/arcadion7-p3", label: "Arcadion7 p 3" },
  { key: "arena/arcadion7", label: "Arcadion 7" },
  { key: "arena/arcadion8-p2", label: "Arcadion8 p 2" },
  { key: "arena/arcadion8-sp2-mirror", label: "Arcadion8 sp2 mirror" },
  { key: "arena/arcadion8-sp2", label: "Arcadion8 sp 2" },
  { key: "arena/arcadion8", label: "Arcadion 8" },
  { key: "arena/cloud-deck", label: "Cloud deck" },
  { key: "arena/e11", label: "E 11" },
  { key: "arena/e8", label: "E 8" },
  { key: "arena/everkeep", label: "Everkeep" },
  { key: "arena/jury_light", label: "Jury light" },
  { key: "arena/p10", label: "P 10" },
  { key: "arena/p11", label: "P 11" },
  { key: "arena/p12-p2", label: "P12 p 2" },
  { key: "arena/p12", label: "P 12" },
  { key: "arena/p12_checker", label: "P12 checker" },
  { key: "arena/p12_checker2", label: "P12 checker 2" },
  { key: "arena/p12_octagon", label: "P12 octagon" },
  { key: "arena/p7", label: "P 7" },
];

/* ------------------------------------------------------------------ lookups */

import { roleOf } from "./jobs";

/**
 * Resolve anything an entity may carry in an image field to a URL:
 * an asset key ("marker/attack1"), an absolute URL, or a ready-made path.
 */
export function assetUrl(src: string | undefined): string | undefined {
  if (!src) return undefined;
  if (/^(https?:|data:|\/)/.test(src)) return src;
  const file = ASSETS[src] ?? ASSETS[src.replace(/\.(png|svg)$/, "")];
  return file ? `/assets/${file}` : undefined;
}

const PARTY_SLOT_ICONS: Record<string, string> = {
  MT: "actor/tank1",
  OT: "actor/tank2",
  T1: "actor/tank1",
  T2: "actor/tank2",
  H1: "actor/healer1",
  H2: "actor/healer2",
  M1: "actor/melee1",
  M2: "actor/melee2",
  R1: "actor/ranged1",
  R2: "actor/ranged2",
  // The older dps names, in the order a party list uses: melees first.
  D1: "actor/dps1",
  D2: "actor/dps2",
  D3: "actor/dps3",
  D4: "actor/dps4",
};

const ROLE_ICONS: Record<string, string> = {
  tank: "actor/tank",
  healer: "actor/healer",
  melee: "actor/melee",
  ranged: "actor/physical_ranged",
  caster: "actor/magic_ranged",
  dps: "actor/dps",
  any: "actor/any",
};

/** Icon for a player token: job art, else the party slot, else the role. */
export function jobIconKey(job: string, name?: string): string {
  const upper = job.toUpperCase();
  if (ASSETS[`actor/${upper}`]) return `actor/${upper}`;
  const role = ROLE_ICONS[roleOf(job)];
  const slot =
    (name && PARTY_SLOT_ICONS[name.toUpperCase()]) || PARTY_SLOT_ICONS[upper] || undefined;
  // A generic D1..D4 slot loses to a job that already says melee / ranged / caster.
  if (slot && !(slot.startsWith("actor/dps") && role && role !== ROLE_ICONS.dps)) return slot;
  return role ?? "actor/any";
}

/** Enemy art scales with hitbox size, the way XIVPlan's presets do. */
export function enemyIconKey(size: number): string {
  if (size >= 250) return "actor/enemy_huge";
  // The default boss is 120 across, and a boss should look like one.
  if (size >= 120) return "actor/enemy_large";
  if (size >= 90) return "actor/enemy_medium";
  return "actor/enemy_small";
}

export function waymarkIconKey(marker: string): string {
  return `marker/waymark_${marker.toLowerCase()}`;
}
